Add files via upload
This component has certain props like: 
propTypes: {
        placeHolder: PropTypes.string,
        iStyle: PropTypes.object, 
        error: PropTypes.string,
        OnChange: PropTypes.func.isRequired,
        type: PropTypes.string,
        showError: PropTypes.bool,
        regexType: PropTypes.string, // regex for email, mobile, full name, number, input field based on {boolean value}
        value: PropTypes.string, 
        clear: PropTypes.bool, // clear input field based on {boolean value}
        disabled: PropTypes.bool,   // disable input field based on {boolean value}
        OnKeyPress: PropTypes.func, // onKeypress enter calls a functions
        ClassName: PropTypes.string
    }



import CInput from '../components/CInput'; //src path of this JS file

export default class Sample extends React.Component {
  constructor(props) {
   super(props);
      this.state = {
       Name: '',
       isValid: true,
        clear: false,
    }
      this.updateName = this.updateName.bind(this);
  }
  updateName(valueObj){
        console.log(valueObj);
        this.setState({clear: false, Name: valueObj.isValid ? valueObj.value : ''});
    },
  render() {
    return (
      <CInput ClassName="input-field" iStyle = {{ width: '100%', fontSize:'20px' }} regexType="fullname" clear={this.state.clear} 
        placeHolder="Full Name" type="text" showError={ !this.state.isValid } required={true} OnChange = {(value) => 
        this.updateName(value) } error="Name cannot be blank" />
    );
  }
}